[package]
name = "gitv"
version = "0.4.3"
authors = ["jimvdl <jimvdlind@gmail.com>"]
repository = "https://github.com/jimvdl/gitv"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.147", features = ["derive"]}
toml = "0.5.9"