[package]
name = "gitv"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"]}
toml = "0.5.9"